name: flutter_google_places_hoc081098
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice. Better flutter_google_places, updated by @hoc081098
version: 1.0.0-nullsafety.4
homepage: https://github.com/hoc081098/flutter_google_places
repository: https://github.com/hoc081098/flutter_google_places

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.1.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.3
  rxdart: ^0.27.1
  listenable_stream: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  assets:
    - packages/flutter_google_places_hoc081098/assets/google_black.png
    - packages/flutter_google_places_hoc081098/assets/google_white.png
